### ISSUE TITLE
PcapDotNet.Core.dll not found

### ISSUE THREAD

**Issue by keshavsp** [daniel0x00/r2dr2-udp-drdos-tool#2]
I get the following error when trying to run the executable (r2dr2-udp-drdos-tool-master\Binary\r2dr2.exe). Looks like I need it from http://pcapdotnet.codeplex.com/wikipage?title=Using%20Pcap.Net%20in%20your%20programs to fix it:

"Could not load file or assembly 'PcapDotNet.Core.dll' or one of it's dependencies.  The specified module could not be found."

"
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'PcapDotNet.Core.dll' or one of its dependencies. The specified module could not be found.
File name: 'PcapDotNet.Core.dll'
   at UDPRequester.FormBase.FormBase_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

r2dr2
    Assembly Version: 0.9.0.2
    Win32 Version: 0.9.0.2
##     CodeBase: file:///C:/Users/Keshav/Downloads/r2dr2-udp-drdos-tool-master/r2dr2-udp-drdos-tool-master/Binary/r2dr2.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box. "

**Comment by daniel0x00** [comment]
You have to entirely download /Binary folder, with all 5 .dlls. Then,
run r2dr2.exe, that have to be in the same folder where dlls are.

Please tell me if you can't run the app after doing that.

Best regards,
Daniel.

2014-07-14 19:02 GMT+02:00 keshavsp notifications@github.com:

> I get the following error when trying to run the executable
> (r2dr2-udp-drdos-tool-master\Binary\r2dr2.exe). Looks like I need it from
> http://pcapdotnet.codeplex.com/wikipage?title=Using%20Pcap.Net%20in%20your%20programs
> to fix it:
> 
> "Could not load file or assembly 'PcapDotNet.Core.dll' or one of it's
> dependencies. The specified module could not be found."
> 
> "
> See the end of this message for details on invoking
> just-in-time (JIT) debugging instead of this dialog box.
> 
> *************\* Exception Text **************
> System.IO.FileNotFoundException: Could not load file or assembly
> 'PcapDotNet.Core.dll' or one of its dependencies. The specified module
> could not be found.
> File name: 'PcapDotNet.Core.dll'
> at UDPRequester.FormBase.FormBase_Load(Object sender, EventArgs e)
> at System.Windows.Forms.Form.OnLoad(EventArgs e)
> at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
> at System.Windows.Forms.Control.CreateControl()
> at System.Windows.Forms.Control.WmShowWindow(Message& m)
> at System.Windows.Forms.Control.WndProc(Message& m)
> at System.Windows.Forms.Form.WmShowWindow(Message& m)
> at System.Windows.Forms.Form.WndProc(Message& m)
> at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg,
> IntPtr wparam, IntPtr lparam)
> 
> *************\* Loaded Assemblies **************
> mscorlib
> Assembly Version: 4.0.0.0
> Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
>  CodeBase:
> file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> 
> r2dr2
> Assembly Version: 0.9.0.2
> Win32 Version: 0.9.0.2
>  CodeBase:
> file:///C:/Users/Keshav/Downloads/r2dr2-udp-drdos-tool-master/r2dr2-udp-drdos-tool-master/Binary/r2dr2.exe
> 
> System.Windows.Forms
> Assembly Version: 4.0.0.0
> Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
>  CodeBase:
> file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> 
> System
> Assembly Version: 4.0.0.0
> Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
>  CodeBase:
> file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> 
> System.Drawing
> Assembly Version: 4.0.0.0
> Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
>  CodeBase:
> file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> 
> Accessibility
> Assembly Version: 4.0.0.0
> Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
>  CodeBase:
> file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> 
> *************\* JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box. "
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/daniel0x00/r2dr2-udp-drdos-tool/issues/2.

## 

Daniel

**Comment by keshavsp** [comment]
yes, that resolved it.  Thanks.
Keshav

Date: Mon, 14 Jul 2014 18:20:00 -0700
